### ISSUE TITLE
CFScript - error with function as argument type

### ISSUE THREAD

**Issue by TMcKinley** [softwareCobbler/cfc#1]
`component {
	private struct function getDefinedArguments(required function func1, function func2) {
		return {};
	}
}`

Gives me the following errors:
{
	"resource": "/Base.cfc",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Expected '<lexeme>'",
	"source": "cfls",
	"startLineNumber": 2,
	"startColumn": 54,
	"endLineNumber": 2,
	"endColumn": 55
},
{
	"resource": "/Base.cfc",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Reserved keyword `function` cannot be used as a variable name.",
	"source": "cfls",
	"startLineNumber": 2,
	"startColumn": 55,
	"endLineNumber": 2,
	"endColumn": 63
},
{
	"resource": "/Base.cfc",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Names in this position will be discarded at runtime; are you missing a comma?",
	"source": "cfls",
	"startLineNumber": 2,
	"startColumn": 64,
	"endLineNumber": 2,
	"endColumn": 69
},
{
	"resource": "/Base.cfc",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Expected '<lexeme>'",
	"source": "cfls",
	"startLineNumber": 2,
	"startColumn": 70,
	"endLineNumber": 2,
	"endColumn": 71
},
{
	"resource": "/Base.cfc",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Reserved keyword `function` cannot be used as a variable name.",
	"source": "cfls",
	"startLineNumber": 2,
	"startColumn": 71,
	"endLineNumber": 2,
	"endColumn": 79
},
{
	"resource": "/Base.cfc",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Names in this position will be discarded at runtime; are you missing a comma?",
	"source": "cfls",
	"startLineNumber": 2,
	"startColumn": 80,
	"endLineNumber": 2,
	"endColumn": 85
}

It doesn't appear that required or optional arguments make any difference. This seems to work fine in cftags syntax.

https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-a-b/cfargument.html

Thanks!

**Comment by softwareCobbler** [comment]
willfix, this should be valid syntax

**Comment by softwareCobbler** [comment]
fixed in 1.0.21 (should be live anytime now)
now `private function function f(function f) {}` is valid

(too bad `function` cannot be used as an identifier because then we could do
```
private function function function(function function) {}
```

**Comment by TMcKinley** [comment]
Look great, thanks for the quick fix!
