### ISSUE TITLE
Mapping Format

### ISSUE THREAD

**Issue by michaelalandawson** [softwareCobbler/cfc#12]
I ran the script that generates the mapping config and got a 500 error during a string replace.  I'm running Adobe's CF2021.

It did not like the line with "substring1" and "substring2".

Can you give an example of what the mapping result should look like in JSON?

Also, I have a mapping of "/" that points to the wwwroot folder.  Running the script replaces "/" with "", giving me a structure with an empty key.

Thanks!

**Comment by softwareCobbler** [comment]
This feature basically needs a lot more work. It's really experimental tier, it works-ish (on my machine!) but we should mark it as alpha, with a floating api.
