### ISSUE TITLE
Doesn't recognize typed array variants

### ISSUE THREAD

**Issue by tclimis** [softwareCobbler/cfc#13]
CF2018 added typed arrays: https://helpx.adobe.com/coldfusion/developing-applications/the-cfml-programming-language/using-arrays-and-structures/populating-arrays-with-data.html#typed-array

It looks like the parser recognizes the `arrayNew["type"](1)` syntax outlined in the link above. But it doesn't recognize the alternate `["type"][...]` literal syntax (which is not in that document, but is detailed here: https://coldfusion.adobe.com/2018/07/arrays-and-string-enhancements-in-coldfusion-2018/)

It also has problems when using typed arrays in return types and argument types in function definitions, like so:
`string[] function findPropertyFromComponents(required Component[] components) {`

**Comment by softwareCobbler** [comment]
Thanks for the report. This should be fixed in 1.0.47, available in the next few minutes.
