### ISSUE TITLE
Destructuring is flagged as a problem

### ISSUE THREAD

**Issue by michaelalandawson** [softwareCobbler/cfc#14]
The following, valid destructuring code is flagged as a problem:

```
sources["seasons"].each((item, index) => {
	var {name, seasonId, seasonState} = item;
	camps.append({seasonId, name, seasonState});
});
```

![image](https://user-images.githubusercontent.com/39276677/215372256-028b8ece-1887-4a19-b94f-a30bc39be6f6.png)

The problem is:

`Left-hand side of assignment is not a valid assignment target. cfls`

Thanks!

**Comment by softwareCobbler** [comment]
Thanks for the report. I have been wondering if anyone would hit this omission (as in, what is the intersection between people using this and ACF2021's destructuring syntax).

It seems they support recursive destructuring, pretty much as good as JS. It does not seem they support destructuring in function call argument position, e.g. `[{bar:42}].map(({bar}) => bar) // [42]`, but if I'm mistaken about that we can do that too.

Should be good in 1.0.46, which is live any moment now. Please report any regressions; we have tests, but they're not exhaustive.

**Comment by softwareCobbler** [comment]
Oh we need to support spread/rest, too, that's not done yet.

**Comment by michaelalandawson** [comment]
You're welcome.  Thank you for making the change.  VS Code is happy again.

I've been trying the newer features of CF2021 and enjoying the struct- and array-related additions.

Yeah, I'm surprised they added this feature and it actually works without having to deal with issues for a few versions.

**Comment by softwareCobbler** [comment]
Ok, we parse 'rest' now, as in `var {x, ...rest} = {/*...*/}` and `var [x, ...rest] = [/*...*/]`, so that should finish this off.
