### ISSUE TITLE
Goto definition

### ISSUE THREAD

**Issue by ghedwards** [softwareCobbler/cfc#7]
I just want to say, this project looks awesome

Over time we've developed our own framework and been using sublime text as our editor because its quite good at indexing our projects and use of the goto definition.

I've noticed the function / goto definition works quite nicely within the same file, but its not currently finding any definitions in other CFC files. Is there something I can do to help?

Cheers
Gareth.

**Comment by ghedwards** [comment]
We have getController and a getService functions, though how the are accessed varies the functions are the same throughout and return an instance or a singleton of a CFC, I wonder if it would be possible to extend the wirebox getInstance behaviour to work with different function names? How are the CFC paths then obtained?

uses can be like _parent.getService("notes").notesFunction(...) or getService("notes").notesFunction(...) or similar.

**Comment by softwareCobbler** [comment]
hey thanks for trying it out!

> ...but its not currently finding any definitions in other CFC files....

The default resolution algo just walks up the project tree from point-of-use, looking for a filename that matches the typename. This obviously only works in trivial cases; so there is (rough) support for a mappings file to aid resolution. There is a "mappings file generator" available by running the "generate coldfusion mappings script" command:

```
open at least a single coldfusion file to kick off the plugin
press F1 > type 'coldfusion' > the command should be an option in the menu
should open the file so you can copy it
```

The goal there is to run the generated script on your server to generate a JSON dump of the current CF mappings and Wirebox bindings. It might need some tweaking. The json file that your server eventually renders out can then be installed in the project root as cfconfig.json; restart your vscode instance and it should begin using the mappings during intellisense lookups. I think this makes heavy assumptions that your "vscode project folder root" matches the "mappings root", which is, uh, usually correct? Maybe not.

If resolution is working, expressions like the following should produce autocomplete/goto-definition

```
var x = new Some.Type.You.Know.Is.Legit().<autocomplete here>;
// or
function foo(Some.Type.You.Know.Is.Legit arg1) {
    arg1.<autocomplete here>
}
```

> I wonder if it would be possible to extend the wirebox getInstance behaviour to work with different function names? How are the CFC paths then obtained?

Assuming "regular lookup" is working (i.e. the mappings file is participating in resolution), it is possible to turn on all the experimental features (`file > preferences > settings > search 'cflsp'`) and then use the type annotation feature to annotate functions as having the type of the magic-compiler-wirebox-builtin, like:

```
/**
* magic type annotation syntax is (in a comment) "@!type <type>"
* With wirebox resolution on, Wirebox.getInstance is a magically available type
* @!type Wirebox.getInstance
*/
function getService() {
  // whatever
}

function foo() {
    getService("<wirebox-binding-autocomplete-here>").<autocomplete if the binding was resolved>
}
```

**Comment by ghedwards** [comment]
Could you give me an example of what a cfconfig.json file with wirebox mappings looks like ?

**Comment by softwareCobbler** [comment]
the existing format is a simple JSON format
```
{
  "cf": {
    "someCfMapping": "/some/path",
    ...
  }
  "wirebox": {
    "someWireboxBinding@foobar": "someCfMapping"
  }
}
```

**Comment by ghedwards** [comment]
any chance there could be a flag to make definitions global ? like how sublime text indexes functions globally and allows selection of specific definitions ?

**Comment by softwareCobbler** [comment]
Maybe something like that — the spiritual cousin to a typescript ambient declaration. I think typescript allows `env.d.ts` files to magically inject symbols in the global namespace, I was thinking of `env.d.cfm` but a `.cfm` file might picked up by the CF runtime, and that is not desired.

I'm curious how sublime text configures a user's environment, maybe they just stuff it all into a `.sublime/*` and call it a day?
