### ISSUE TITLE
Ability to disable type checking ?

### ISSUE THREAD

**Issue by ghedwards** [softwareCobbler/cfc#8]
Might you provide the ability to disable type checking errors ?

**Comment by softwareCobbler** [comment]
Type errors should be off by default, although I think we were talking about turning related features on for `getInstance` autocomplete purposes. If that's the case, probably we can get away with just the "parse types" option, so it can recognize the annotations that would say "hey this is actually a getInstance function type". That option by its lonesome shouldn't (?!) issue type error diagnostics.
